# Generated by Django 4.1.2 on 2022-12-26 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Order Status',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finish', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_order', models.CharField(blank=True, max_length=26, null=True)),
                ('session_id', models.CharField(blank=True, max_length=61, null=True)),
                ('amount', models.FloatField(blank=True, max_length=17, null=True)),
                ('vci', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('card_number', models.CharField(blank=True, max_length=19, null=True)),
                ('accounting_date', models.CharField(blank=True, max_length=4, null=True)),
                ('transaction_date', models.CharField(blank=True, max_length=24, null=True)),
                ('authorization_code', models.CharField(blank=True, max_length=6, null=True)),
                ('payment_type_code', models.CharField(blank=True, max_length=10, null=True)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('installments_amount', models.IntegerField(blank=True, max_length=17, null=True)),
                ('installments_number', models.IntegerField(blank=True, max_length=2, null=True)),
                ('balance', models.CharField(blank=True, max_length=17, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payments History',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.IntegerField()),
                ('total', models.IntegerField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.orderstatus')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/Invoices/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.order')),
            ],
        ),
    ]
